"""从零实现 Tiny ViT 的可复用组件。"""

from .config import (
    BATCH_SIZE,
    BEST_MODEL_PATH,
    CHECKPOINT_DIR,
    CONFUSION_MATRIX_PATH,
    DATA_ROOT,
    DROPOUT_RATE,
    EMBED_DIM,
    EVALUATION_SUMMARY_PATH,
    IMAGE_SIZE,
    IN_CHANNELS,
    LEARNING_RATE,
    LOG_INTERVAL,
    MAX_GRAD_NORM,
    MIN_LEARNING_RATE,
    MLP_HIDDEN_DIM,
    NUM_CLASSES,
    NUM_ENCODER_BLOCKS,
    NUM_EPOCHS,
    NUM_HEADS,
    NUM_WORKERS,
    PATCH_SIZE,
    RANDOM_SEED,
    RESULTS_DIR,
    SAMPLE_PREDICTIONS_PATH,
    TRAINING_CURVES_PATH,
    TRAINING_HISTORY_PATH,
    VALIDATION_SIZE,
    WEIGHT_DECAY,
)
from .data import create_cifar10_dataloaders
from .embedding import PatchEmbedding, ViTInputEmbedding
from .encoder import (
    AttentionSubLayer,
    EncoderBlock,
    MLPSubLayer,
    TransformerEncoder,
)
from .evaluation import (
    collect_evaluation_results,
    load_training_history,
    plot_confusion_matrix,
    plot_prediction_samples,
    plot_training_history,
    save_evaluation_summary,
)
from .model import ClassificationHead, TinyViT, extract_cls_token
from .training import (
    create_training_components,
    evaluate,
    fit,
    set_random_seed,
    train_one_epoch,
)

__all__ = [
    "AttentionSubLayer",
    "BATCH_SIZE",
    "BEST_MODEL_PATH",
    "CHECKPOINT_DIR",
    "CONFUSION_MATRIX_PATH",
    "ClassificationHead",
    "DATA_ROOT",
    "DROPOUT_RATE",
    "EMBED_DIM",
    "EVALUATION_SUMMARY_PATH",
    "EncoderBlock",
    "IMAGE_SIZE",
    "IN_CHANNELS",
    "LEARNING_RATE",
    "LOG_INTERVAL",
    "MAX_GRAD_NORM",
    "MIN_LEARNING_RATE",
    "MLPSubLayer",
    "MLP_HIDDEN_DIM",
    "NUM_CLASSES",
    "NUM_ENCODER_BLOCKS",
    "NUM_EPOCHS",
    "NUM_HEADS",
    "NUM_WORKERS",
    "PATCH_SIZE",
    "PatchEmbedding",
    "RANDOM_SEED",
    "RESULTS_DIR",
    "SAMPLE_PREDICTIONS_PATH",
    "TinyViT",
    "TRAINING_CURVES_PATH",
    "TRAINING_HISTORY_PATH",
    "TransformerEncoder",
    "VALIDATION_SIZE",
    "ViTInputEmbedding",
    "WEIGHT_DECAY",
    "create_cifar10_dataloaders",
    "create_training_components",
    "collect_evaluation_results",
    "evaluate",
    "extract_cls_token",
    "fit",
    "load_training_history",
    "plot_confusion_matrix",
    "plot_prediction_samples",
    "plot_training_history",
    "save_evaluation_summary",
    "set_random_seed",
    "train_one_epoch",
]
