"""CIFAR-10 CNN 公平对照模型。"""

from .config import (
    CNN_CHECKPOINT_PATH,
    CNN_CONFUSION_MATRIX_PATH,
    CNN_EVALUATION_SUMMARY_PATH,
    CNN_HISTORY_PATH,
    CNN_RESULTS_DIR,
    CNN_SAMPLE_PREDICTIONS_PATH,
    CNN_TRAINING_CURVES_PATH,
)
from .model import CNNBaseline, ConvStage

__all__ = [
    "CNNBaseline",
    "CNN_CHECKPOINT_PATH",
    "CNN_CONFUSION_MATRIX_PATH",
    "CNN_EVALUATION_SUMMARY_PATH",
    "CNN_HISTORY_PATH",
    "CNN_RESULTS_DIR",
    "CNN_SAMPLE_PREDICTIONS_PATH",
    "CNN_TRAINING_CURVES_PATH",
    "ConvStage",
]
