"""自定义 Swin 网络项目中，模型构建前可复用的配置和数据接口。"""

from .config import (
    ATTENTION_DROPOUT_RATE,
    BATCH_SIZE,
    BEST_MODEL_PATH,
    CHECKPOINT_DIR,
    DATA_ROOT,
    DROPOUT_RATE,
    EMBED_DIM,
    EVALUATION_SUMMARY_PATH,
    IMAGE_SIZE,
    IN_CHANNELS,
    LABEL_SMOOTHING,
    LEARNING_RATE,
    LOG_INTERVAL,
    MAX_GRAD_NORM,
    MIN_LEARNING_RATE,
    MLP_RATIO,
    NUM_CLASSES,
    NUM_EPOCHS,
    NUM_WORKERS,
    PATCH_SIZE,
    RANDOM_SEED,
    RESULTS_DIR,
    STAGE_DEPTHS,
    STAGE_DIMS,
    STAGE_NUM_HEADS,
    STAGE_USE_SHIFTED_WINDOWS,
    STOCHASTIC_DEPTH_RATE,
    TRAINING_HISTORY_PATH,
    VALIDATION_SIZE,
    WARMUP_EPOCHS,
    WEIGHT_DECAY,
    WINDOW_SIZE,
)
from .data import create_cifar100_dataloaders
from .embedding import PatchEmbedding
from .encoder import (
    DropPath,
    MLP,
    PatchMerging,
    SwinBlock,
    SwinStage,
    WindowAttention,
    create_shifted_window_mask,
    window_partition,
    window_reverse,
)
from .model import AttentionPooling, ClassificationHead, CustomSwin


__all__ = [
    "ATTENTION_DROPOUT_RATE",
    "AttentionPooling",
    "BATCH_SIZE",
    "BEST_MODEL_PATH",
    "CHECKPOINT_DIR",
    "ClassificationHead",
    "CustomSwin",
    "DATA_ROOT",
    "DROPOUT_RATE",
    "DropPath",
    "EMBED_DIM",
    "EVALUATION_SUMMARY_PATH",
    "IMAGE_SIZE",
    "IN_CHANNELS",
    "LABEL_SMOOTHING",
    "LEARNING_RATE",
    "LOG_INTERVAL",
    "MAX_GRAD_NORM",
    "MIN_LEARNING_RATE",
    "MLP_RATIO",
    "MLP",
    "NUM_CLASSES",
    "NUM_EPOCHS",
    "NUM_WORKERS",
    "PATCH_SIZE",
    "PatchEmbedding",
    "PatchMerging",
    "RANDOM_SEED",
    "RESULTS_DIR",
    "STAGE_DEPTHS",
    "STAGE_DIMS",
    "STAGE_NUM_HEADS",
    "STAGE_USE_SHIFTED_WINDOWS",
    "STOCHASTIC_DEPTH_RATE",
    "SwinBlock",
    "SwinStage",
    "TRAINING_HISTORY_PATH",
    "VALIDATION_SIZE",
    "WARMUP_EPOCHS",
    "WEIGHT_DECAY",
    "WINDOW_SIZE",
    "WindowAttention",
    "create_shifted_window_mask",
    "create_cifar100_dataloaders",
    "window_partition",
    "window_reverse",
]
